### ISSUE TITLE
how to get the cell value after reading the excel

### ISSUE THREAD

**Issue by jiaodaxiaozi** [mrjono1/FastExcel#11]
The excel file can be read quickly by the "read" method, but it is not so convenient to query cell values in the worksheet. Now I get those values in a cell-by-cell way and add those values to a Datatable. I wonder whether there is a better way to query the cell values in the worksheet? Thanks!

**Comment by mrjono1** [comment]
Hi

At the moment I don't have any ways to filter the data being read. Adding a for loop and if test on the Worksheet.Rows is the best way to query a worksheet.

**Comment by jiaodaxiaozi** [comment]
Hi mrjono1,

I find out the way to get the cell values after spending several hours, maybe it is because I am not good at using Enumerable values in C#. Here I attach the method that I used. Hope it can help others. Thanks!
`           DataTable RL = new DataTable();
            RL.Columns.Add("t");
            RL.Columns.Add("r");
            RL.Columns.Add("rd");

            // Open excel file using read only is much faster, but you cannot perfrom any writes
            using (FastExcel.FastExcel fastExcel = new FastExcel.FastExcel(inputFile, true))
            {
                Worksheet worksheet0 = fastExcel.Read("RL", 1);
                enuToDatatable(worksheet0, RL);
            }
        /// <summary>
        /// Transform enumerator to datatable
        /// </summary>
        /// <param name="worksheet"></param>
        /// <param name="data"></param>
        public static void enuToDatatable(Worksheet worksheet, DataTable data)
        {
            IEnumerator enumerator = worksheet.Rows.GetEnumerator();

            int count = 0;

            while (enumerator.MoveNext())
            {
                if (count > 0)
                {
                    Row row = (Row)enumerator.Current;

                    IEnumerator enumerator1 = row.Cells.GetEnumerator();

                    DataRow dt = data.NewRow();

                    int i = 0;

                    while (enumerator1.MoveNext())
                    {
                        Cell cell = (Cell)enumerator1.Current;
                        dt[i] = int.Parse(cell.Value.ToString());
                        i = i + 1;
                    }

                    data.Rows.Add(dt);
                }

                count += 1;
            }
        }
`

**Comment by mrjono1** [comment]
Hi jiaodaxiaozi 

I'm glad you figured it out :)

I have updated your code to use a foreach, although I have not tested it. I should probably add this to the project.

You might want to do some reading up on for/foreach loops in C# they are heaps easier than while and less chances of bugs. :)
This website is a great help https://www.dotnetperls.com/for-foreach

`DataTable RL = new DataTable();
         RL.Columns.Add("t");
         RL.Columns.Add("r");
         RL.Columns.Add("rd");

         // Open excel file using read only is much faster, but you cannot perfrom any writes
        using (FastExcel.FastExcel fastExcel = new FastExcel.FastExcel(inputFile, true))
        {
             Worksheet worksheet0 = fastExcel.Read("RL", 1);
              enuToDatatable(worksheet0, RL);
         }
        /// <summary>
        /// Transform enumerator to datatable
        /// </summary>
        /// <param name="worksheet"></param>
        /// <param name="data"></param>
        public static void enuToDatatable(Worksheet worksheet, DataTable data)
        {
            foreach (var row in worksheet.Rows)
             {
                 foreach(var cell in row.Cells)
                 {
                        dt[cell.ColumnNumber] = int.Parse(cell.Value.ToString());
                    }
                    data.Rows.Add(dt);
                }
            }
        }`
