### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mrjono1** [mrjono1/FastExcel#19]
need to add unit tests to project

**Comment by TimSirmovics** [comment]
Is this open for anybody to start off a test project or do you want to set up the structure yourself?

**Comment by Sibz** [comment]
I am not so good with tests, and @mrjono1 doesn't have as much time available to contribute these days so I think you are very welcome to kick start this off.

**Comment by hthroweriii** [comment]
@mrjono1 @TimSirmovics Any more progress on this? I'd like to help out if i can.

**Comment by mrjono1** [comment]
Hi @hthroweriii, unfortunately no progress, if you can help out that would be great!

**Comment by hthroweriii** [comment]
@mrjono Awesome! I'll get started on it.
