### ISSUE TITLE
Row style and big data

### ISSUE THREAD

**Issue by FabielFRS** [mrjono1/FastExcel#25]
Hello

Firstly, I would like to congratulate you on your work.

Come on.

I have 2 problems.

Is it possible to paint the first line, or even make a zebra?

I tried to generate a file with 700,000 rows and 70 columns and got the exception (OutOfMemory) returned at the moment "fastExcel.Write (worksheet," sheet1 ");", any solution to this?

**Comment by mrjono1** [comment]
Come on? why would I want to help you saying that.

This project does not support formatting
