### ISSUE TITLE
Object reference error while reading a Excel 2007 file

### ISSUE THREAD

**Issue by mukeshshah1020** [mrjono1/FastExcel#26]
The fastExcel.Read method in the following code throws "Object reference not set to an instance of an object" exception for _some_ excel files. A sample excel file is attached.

                FileInfo inputFile = new FileInfo(filePath);
                using (FastExcel.FastExcel fastExcel = new FastExcel.FastExcel(inputFile, true))
                {
                    var worksheet = fastExcel.Read(1, 1);
                }

[RouteMaster.xlsx](https://github.com/mrjono1/FastExcel/files/1641782/RouteMaster.xlsx)

**Comment by mrjono1** [comment]
this issue should be resolved in 2.2.10 release
