### ISSUE TITLE
Why can't I iterate over all worksheets?

### ISSUE THREAD

**Issue by Corillian** [mrjono1/FastExcel#3]
From an API design standpoint `worksheet = fastExcel.Read("sheet1");` doesn't really make any sense. Why can't I do something like the following:

```C#
foreach(var curWorksheet in fastExcelt.WorkSheets)
{
    Console.WriteLine(curWorksheet.Name);
}
```

**Comment by mrjono1** [comment]
Hi Coriliian, this feature has not been implemented it is also the first feature request I have had so far, so its not surprising there is things missing.

I have just done a bit of reviewing of the code base and this sounds like a good feature to add.

**Comment by mrjono1** [comment]
This feature has been added b1016af56395259be0a2116f9c01c6a0f6070c8b
