### ISSUE TITLE
Demo gives me errors

### ISSUE THREAD

**Issue by DanteNahuel** [mrjono1/FastExcel#32]
When trying the Read Demo I get that DataSet and FileInfo can't be found. if I include System.Data, then fastExcel.Read stops working.

**Comment by kpstolk** [comment]
Same with the Write Demo (demo 1).

If there's no existing file a `NullReferenceException` is thrown.
Seems to fail at [`GetEntry("xl/workbook.xml")` L538](https://github.com/mrjono1/FastExcel/blob/4cbc91f4c32c3bb194308e305cbdafa3e0ead1e2/FastExcel/Worksheet.cs#L538), so an existing file is expected?

If I create a `.xlsx` file beforehand I get another exception `Exception: 'There is no sheet named 'sheet3''`.

**Comment by mrjono1** [comment]
I have found the issue, i should have a fix soon

**Comment by mrjono1** [comment]
@DanteNahuel I have fixed your issue, the readme has been updated.
@kpstolk I have fixed a null reference bug that should fix your issue
