### ISSUE TITLE
Initialize with a stream

### ISSUE THREAD

**Issue by MaciejWierzchowski** [mrjono1/FastExcel#37]
Would it make sense to initialize the `FastExcel` with a stream instead of `FileInfo`?

**Comment by kjkrum** [comment]
This could be useful for ASP.NET MVC controllers. `HttpPostedFileBase` contains a stream which currently must be written to a file to be read by `FastExcel`.

**Comment by mrjono1** [comment]
For reading or writing each has a very different approach

**Comment by NeverMine17** [comment]
Also in UWP you can't write or read anything by file name directly. @mrjono1

**Comment by mrjono1** [comment]
I would prefer to use a stream but;
I don't know any way to read excel using a stream,
I also don't know any way to write to excel using a stream

from my understanding an excel file content is to complex for this approach

**Comment by mrjono1** [comment]
This has been completed https://github.com/mrjono1/FastExcel/pull/54

**Comment by nm17** [comment]
@mrjono1 A year after, finally :smile:
