### ISSUE TITLE
Cell Format (Font Color, Font Style, Cell back Color ..Etc)

### ISSUE THREAD

**Issue by frahman2** [mrjono1/FastExcel#48]
Hi,

Thank you for your efforts, please does that support cell formatting? and if yes, please how can I call that?
Regards,
Firas

**Comment by mrjono1** [comment]
Hi @frahman2 sorry but this library is only for basic fast read and write. Formatting isnt going to be added to the project

**Comment by frahman2** [comment]
Hi,

Thank you, thanks for your effort.
Regards,
Firas

**Comment by mrjono1** [comment]
Thankyou for your interest, you will find a fully featured package
