### ISSUE TITLE
Looking for a new owner

### ISSUE THREAD

**Issue by mrjono1** [mrjono1/FastExcel#56]
Hi, I am no longer interested in owning this project

There is nuget, repo and the appveyor to hand over

post a reply here if you are interested

**Comment by ahmedwalid05** [comment]
Hello, 
I am willing to take over the project and maintain it if no one else is interested.

**Comment by mrjono1** [comment]
@ahmedwalid05 sounds good to me, I'll have to figure out how to give you the nuget

**Comment by ahmedwalid05** [comment]
Of Course. My email is ahmedwalid05@gmail.com if you want to contact me privately.

**Comment by mrjono1** [comment]
Ive sent you an email if you want to delete you email from here
