### ISSUE TITLE
it supports the netcore?

### ISSUE THREAD

**Issue by judypol** [mrjono1/FastExcel#7]
Hi it supports the netcore?

**Comment by mrjono1** [comment]
I haven't tried it with .net core yet, if you have a chance to try it out it would be great to get your feedback on it.

**Comment by mahmoud200m** [comment]
I tested and it works with asp.net core v1.0 using .NetFramework not sure about Core one

**Comment by mrjono1** [comment]
I tried it on core and it didn't work, I think I have found one line of code that is making it incompatible, on a feature that is not documented

**Comment by mrjono1** [comment]
it now supports netcore! and many other .net flavors using the .NetStandard library

**Comment by mrjono1** [comment]
Currently in pre-release on nuget
