### ISSUE TITLE
Convert number to text column

### ISSUE THREAD

**Issue by saraththe** [mrjono1/FastExcel#8]
Hello,

I have some values in a column which start with zero for example, 00072 which a valid word. Before exporting to excel I verified in datatable and the array you used rawData[row + 1, col], it is showing as 00072 only. But when it comes to excel, it is showing 72.

Note that none of the values in this column has a character.

Can you please help here?

Thanks in advance,
Sarath.K.S
+919645809996

**Comment by Sibz** [comment]
Does putting a single quote in front fix the issue. I.e. '00079  should be shown as 00079 in excel. Note that with this approach, excel treats the number as text therfore can't be apart of any number calculations.

**Comment by mrjono1** [comment]
What datatype is rawData[row + 1, col] ?
If it is a 'string' then this should not be happening but if it is any other type this is the behavior of Excel, it's not nice but you do need to be specific to keep leading zeros.

FYI: Through the Excel UI you need to set a column to 'Text' which is the same as setting it as a 'string' in this project

**Comment by mrjono1** [comment]
Closing due to no response
