### ISSUE TITLE
collaborators

### ISSUE THREAD

**Issue by mrjono1** [mrjono1/FastExcel#9]
@Sibz are you interested in being a collaborator on this project?

**Comment by Sibz** [comment]
Sure, I like to help out with questions where I can. If I get bored might even try that add new sheet function. I am happy to leave merging pull requests to you though.
I've found this project great as a lightweight way of importing data from Excel, I have another project needing it that I will probably start on in January.

You can email me steven at entityzero dot com - I'll remove the email from the comment once you've contacted me.
